### PR TITLE
Dummy main

### PR DESCRIPTION
**Pull request by eshza**

### CODE REVIEW

**Review by karimhamdanali — COMMENTED** [review]
@eshza, this PR seems to do the same thing as #9, isn't it?

**Comment by karimhamdanali** [comment]
@eshza so is it indeed a duplicate?

**Comment by eshza** [comment]
@karimhamdanali yes the commits from this branch were already included in #9, so it is a duplicate. Sorry about that.

**Comment by karimhamdanali** [comment]
ah ok, no worries. I was just checking.

**Pull request closed without merging**
